#Duy Nhan Cao

all: expand factor

#expand: expand.o
#	clang++ -Wall -w -o expand expand.o

#factor: factor.o
#	clang++ -o factor factor.o

expand: expand.cpp
	clang++ expand.cpp -o expand -w

factor: factor.cpp
	clang++ factor.cpp -o factor -w

clean:
	rm -f *.o all *~

